class AddMoreToOppty < ActiveRecord::Migration
  def change
    add_column :oppties, :codeName, :string
    add_column :oppties, :descriptionOfWork, :string
    add_column :oppties, :category, :string
    add_column :oppties, :pwald, :string
    add_column :oppties, :pBid, :integer
    add_column :oppties, :awardFV, :integer
    add_column :oppties, :saicvaPercent, :integer
    add_column :oppties, :saicva, :integer
    add_column :oppties, :mat, :integer
    add_column :oppties, :materialsTV, :integer
    add_column :oppties, :subc, :integer
    add_column :oppties, :subTV, :integer
    add_column :oppties, :cg_va, :integer
    add_column :oppties, :sss_va, :integer
    add_column :oppties, :nwi_va, :integer
    add_column :oppties, :hwi_va, :integer
    add_column :oppties, :itms_va, :integer
    add_column :oppties, :tss_va, :integer
    add_column :oppties, :ccds_va, :integer
    add_column :oppties, :mss_va, :integer
    add_column :oppties, :swi_va, :integer
    add_column :oppties, :lsc_va, :integer
    add_column :oppties, :zzOth_va, :integer
    add_column :oppties, :pri, :integer
    add_column :oppties, :aop, :string
    add_column :oppties, :peg, :string
    add_column :oppties, :mustWin, :string
    add_column :oppties, :feeIndic, :string
    add_column :oppties, :slutil, :string
    add_column :oppties, :recompete, :string
    add_column :oppties, :competitive, :string
    add_column :oppties, :international, :string
    add_column :oppties, :strategic, :string
    add_column :oppties, :bundle, :string
    add_column :oppties, :bidReviewStream, :string
    add_column :oppties, :definedDelivPgm, :string
    add_column :oppties, :evaluationCriteria, :string
    add_column :oppties, :perfWorkLoc, :string
    add_column :oppties, :classIfReqmt, :string
    add_column :oppties, :grouping, :string
    add_column :oppties, :reasonForWinLoss, :string
    add_column :oppties, :egr, :float
    add_column :oppties, :slCat, :string
    add_column :oppties, :slPri, :string
    add_column :oppties, :slNote, :string
    add_column :oppties, :crmRunDate, :date
    add_column :oppties, :contractStartDate, :date
    add_column :oppties, :rfpFYPer, :string
    add_column :oppties, :submitFYPer, :string
    add_column :oppties, :awardFYPer, :string
    add_column :oppties, :preBPprojID, :string
    add_column :oppties, :fy16PreBP, :integer
    add_column :oppties, :fy16PreBPSpent, :integer
    add_column :oppties, :fy16PreBPSpentPercent, :integer
    add_column :oppties, :bpProjID, :string
    add_column :oppties, :fy16BDTot, :integer
    add_column :oppties, :fy16BDTotSpent, :integer
    add_column :oppties, :fy16BDTotSpentPercent, :integer
    add_column :oppties, :financeDate, :date
    add_column :oppties, :cgSecOrg, :string
    add_column :oppties, :cgSecMgr, :string
    add_column :oppties, :cgOrg, :string
    add_column :oppties, :cgMgr, :string
    add_column :oppties, :opOrg, :string
    add_column :oppties, :cgOpMgr, :string
    add_column :oppties, :cgPgmDir, :string
    add_column :oppties, :bdMgr, :string
    add_column :oppties, :crmRecOwner, :string
    add_column :oppties, :sslMgr, :string
    add_column :oppties, :divNum, :integer
    add_column :oppties, :customer, :string
    add_column :oppties, :endCustomer, :string
    add_column :oppties, :crn, :integer
    add_column :oppties, :contractType, :string
    add_column :oppties, :opptyClass, :string
    add_column :oppties, :numberOfAwards, :integer
    add_column :oppties, :totalPOP, :integer
    add_column :oppties, :primeSub, :string
  end
end
